name: release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  release-please:
    runs-on: macos-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      browser_finder_release: ${{ steps.release.outputs['packages/browser-finder--release_created'] }}
      playwright_release: ${{ steps.release.outputs['packages/playwright--release_created'] }}
      playwright_core_release: ${{ steps.release.outputs['packages/playwright-core--release_created'] }}
      puppeteer_release: ${{ steps.release.outputs['packages/puppeteer--release_created'] }}
      browsers_release: ${{ steps.release.outputs['packages/puppeteer-browsers--release_created'] }}
      puppeteer_core_release: ${{ steps.release.outputs['packages/puppeteer-core--release_created'] }}
      types_release: ${{ steps.release.outputs['packages/snapka-types--release_created'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: 安装依赖
        run: pnpm install

      - name: 升级 npm 版本
        run: npm install -g npm@latest

      - name: 构建所有包
        run: pnpm -r run build

      - name: 发布 browsers 包
        if: ${{ needs.release-please.outputs.browsers_release == 'true' }}
        working-directory: packages/puppeteer-browsers
        run: pnpm publish

      - name: 发布 types 包
        if: ${{ needs.release-please.outputs.types_release == 'true' }}
        working-directory: packages/snapka-types

        run: pnpm publish
      - name: 发布 playwright-core 包
        if: ${{ needs.release-please.outputs.playwright_core_release == 'true' }}
        working-directory: packages/playwright-core

        run: pnpm publish
      - name: 发布 puppeteer-core 包
        if: ${{ needs.release-please.outputs.puppeteer_core_release == 'true' }}
        working-directory: packages/puppeteer-core

        run: pnpm publish
      - name: 发布 browser-finder 包
        if: ${{ needs.release-please.outputs.browser_finder_release == 'true' }}
        working-directory: packages/browser-finder

        run: pnpm publish
      - name: 发布 playwright 包
        if: ${{ needs.release-please.outputs.playwright_release == 'true' }}
        working-directory: packages/playwright

        run: pnpm publish
      - name: 发布 puppeteer 包
        if: ${{ needs.release-please.outputs.puppeteer_release == 'true' }}
        working-directory: packages/puppeteer
        run: pnpm publish
